version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web:latest
    ports:
      - "80:80"
    depends_on:
      - db
    # volumes:
    #  - ./code:/app/code
    environment:
      MYSQL_HOST: "db" 
      MYSQL_DATABASE: targets
      MYSQL_USER: targets
      MYSQL_PASSWORD: password
      ID: "1234"
    #command: tail -f /etc/fstab
  db:
    image: mysql:8.4.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: targets
      MYSQL_USER: targets
      MYSQL_PASSWORD: password
    volumes:
      - ./seed:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306 