apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql }}
  namespace: {{ .Values.namespace }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.mysql }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql }}
    spec:
      containers:
      - name: {{ .Values.mysql }}
        image: {{ .Values.mysqlImage }}:{{ .Values.mysqlImageTag }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql }}-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql }}-secret
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql }}-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql }}-secret
              key: MYSQL_PASSWORD
        ports:
        - containerPort: {{ .Values.mysqlContainerPort }}
        args: ['--mysql-native-password=ON']
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: {{ .Values.mysqlCpuRequest }}
            memory: {{ .Values.mysqlMemoryRequest }}
          limits:
            cpu: {{ .Values.mysqlCpuLimit }}
            memory: {{ .Values.mysqlMemoryLimit }}
        volumeMounts:
        - name: {{ .Values.mysql }}-data
          mountPath: /var/lib/mysql
        - name: {{ .Values.mysql }}-seed
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: {{ .Values.mysql }}-data
        persistentVolumeClaim:
          claimName: {{ .Values.mysql }}-pvc
      - name: {{ .Values.mysql }}-seed
        configMap:
          name: {{ .Values.mysql }}-seed