apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.mysqlExternalPort }}
    name: {{ .Values.mysql }}
    targetPort: {{ .Values.mysqlInternalPort }}
  selector:
    app: {{ .Values.mysql }}
  type: ClusterIP