apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.web }}
  namespace: {{ .Values.namespace }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
      maxSurge: {{  .Values.maxSurge }}
  selector:
    matchLabels:
      app: {{ .Values.web }}
  template:
    metadata:
      labels:
        app: {{ .Values.web }}
    spec:
      containers:
      - name: {{ .Values.web }}
        env:
        - name: ID
          value: "1234"
        - name: MYSQL_HOST
          value: {{ .Values.mysql }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql }}-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql }}-secret
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql }}-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql }}-secret
              key: MYSQL_PASSWORD
        image: {{ .Values.webImage }}:{{ .Values.webImageTag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.webContainerPort }}
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: {{ .Values.webContainerPort }}
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: {{ .Values.webContainerPort }}
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: {{ .Values.webCpuRequest }}
            memory: {{ .Values.webMemoryRequest }}
          limits:
            cpu: {{ .Values.webCpuLimit }}
            memory: {{ .Values.webMemoryLimit }}