apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.webExternalPort }}
    targetPort: {{ .Values.webInternalPort }}
  selector:
    app: {{ .Values.web }}